apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - mediamtx-configmap.yaml
  - mediamtx-deployment.yaml
  - mediamtx-service.yaml
  - testsrc-deployments.yaml
