apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediamtx
  labels:
    app: mediamtx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediamtx
  template:
    metadata:
      labels:
        app: mediamtx
    spec:
      containers:
        - name: mediamtx
          image: bluenviron/mediamtx:latest-ffmpeg
          ports:
            - containerPort: 8889
              name: webrtc
            - containerPort: 8888
              name: hls
          volumeMounts:
            - name: config
              mountPath: /mediamtx.yml
              subPath: mediamtx.yml
          livenessProbe:
            httpGet:
              path: /v3/paths/list
              port: 9997
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v3/paths/list
              port: 9997
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 512Mi
      volumes:
        - name: config
          configMap:
            name: mediamtx-config
