apiVersion: v1
kind: Service
metadata:
  name: mediamtx
  labels:
    app: mediamtx
spec:
  type: ClusterIP
  selector:
    app: mediamtx
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: webrtc
      port: 8889
      targetPort: 8889
